name       : bleachbit
version    : 1.12
release    : 4
source     :
    - http://ncu.dl.sourceforge.net/project/bleachbit/bleachbit/1.12/bleachbit-1.12.tar.bz2 : 55188debde6ccb9d83ebf5bb9f8c821c616fa0dfe309779d3d87059c04b1a8f4
license    :
    - GPL-2.0
    - GPL-3.0
component  : security
summary    : BleachBit frees disk space and maintains privacy.
description: |
    BleachBit frees disk space and maintains privacy.
builddeps  :
    - pkgconfig(pygtk-2.0)
rundeps    :
    - python-gtk2
    - python-gobject2
install    : |
    %make_install bindir=/usr/bin datadir=/usr/share
