name       : bleachbit
version    : 1.10
release    : 2
source     :
    - http://ncu.dl.sourceforge.net/project/bleachbit/bleachbit/1.10/bleachbit-1.10.tar.bz2 : 33209c8f11a1417ef61231a34a8468831b1583a000330092034568b0904f6948
license    : 
    - GPL-2.0
    - GPL-3.0
summary    : BleachBit frees disk space and maintains privacy.
description: |
    BleachBit frees disk space and maintains privacy.
builddeps  :
    - pkgconfig(pygtk-2.0)
rundeps :
    - python-gtk2
install    : |
   %make_install bindir=/usr/bin datadir=/usr/share
