name       : bleachbit
version    : 4.0.0
release    : 11
source     :
    - https://github.com/bleachbit/bleachbit/archive/v4.0.0.tar.gz : 5f7813b1ecda32647b1a31564b66f369fbd0d50d67924f256a0d414abc07501b
homepage   : https://www.bleachbit.org
license    : GPL-3.0-or-later
component  : security
summary    : BleachBit frees disk space and maintains privacy
description: |
    BleachBit quickly frees disk space and tirelessly guards your privacy. Free cache, delete cookies, clear Internet history, shred temporary files, delete logs, and discard junk you didn't know was there. It wipes clean a thousand applications including Firefox, Adobe Flash, Google Chrome, Opera, and more.
rundeps    :
    - python-gobject
    - python-requests
install    : |
    %make_install bindir=/usr/bin datadir=/usr/share
