name       : bleachbit
version    : 1.8
release    : 1
source     :
    - http://heanet.dl.sourceforge.net/project/bleachbit/bleachbit/1.8/bleachbit-1.8.tar.bz2 : dbf50fcbf24b8b3dd1c4325cd62352628d089f88a76eab804df5d90c872ee592
license    : 
    - GPL-2.0
    - GPL-3.0
summary    : BleachBit frees disk space and maintains privacy.
description: |
    BleachBit frees disk space and maintains privacy.
builddeps  :
    - pkgconfig(pygtk-2.0)
rundeps :
    - python-gtk2
install    : |
   %make_install bindir=/usr/bin datadir=/usr/share
