name       : bleachbit
version    : '2.0'
release    : 6
source     :
    - https://github.com/bleachbit/bleachbit/archive/v2.0.tar.gz : a4bb3089c2120d3e99ed19569f2de0963a6e91f9b8a018315dd22287ed282f97
license    : GPL-3.0-or-later
component  : security
summary    : BleachBit frees disk space and maintains privacy.
description: |
    BleachBit frees disk space and maintains privacy.
builddeps  :
    - pkgconfig(pygtk-2.0)
rundeps    :
    - python-gtk2
    - python-gobject2
install    : |
    %make_install bindir=/usr/bin datadir=/usr/share
