name       : bleachbit
version    : 2.2
release    : 7
source     :
    - https://github.com/bleachbit/bleachbit/archive/v2.2.tar.gz : 5abdf59df4157880347590c8463a2b1bff94467e2cfd988569a90f5cb447292a
license    : GPL-3.0-or-later
component  : security
summary    : BleachBit frees disk space and maintains privacy.
description: |
    BleachBit frees disk space and maintains privacy.
builddeps  :
    - pkgconfig(pygtk-2.0)
rundeps    :
    - python-gtk2
    - python-gobject2
install    : |
    %make_install bindir=/usr/bin datadir=/usr/share