name       : bleachbit
version    : 3.2.0
release    : 9
source     :
    - https://github.com/bleachbit/bleachbit/archive/v3.2.0.tar.gz : c0e25253781d768da4eacf56739bf547dc59f2fe212f44e464f4fcc1bc855e44
homepage   : https://www.bleachbit.org
license    : GPL-3.0-or-later
component  : security
summary    : BleachBit frees disk space and maintains privacy.
description: |
    BleachBit frees disk space and maintains privacy.
builddeps  :
    - pkgconfig(pygtk-2.0)
rundeps    :
    - python-gtk2
    - python-scandir
install    : |
    %make_install bindir=/usr/bin datadir=/usr/share
