name       : bleachbit
version    : 2.0
release    : 5
source     :
    - https://download.bleachbit.org/bleachbit-2.0.tar.bz2 : e9b7bec39574af68e64bf1a0fa70cbebc421a18978fa83974878044bfa47495f
license    : GPL-3.0
component  : security
summary    : BleachBit frees disk space and maintains privacy.
description: |
    BleachBit frees disk space and maintains privacy.
builddeps  :
    - pkgconfig(pygtk-2.0)
rundeps    :
    - python-gtk2
    - python-gobject2
install    : |
    %make_install bindir=/usr/bin datadir=/usr/share
