name       : bleachbit
version    : '3.0'
release    : 8
source     :
    - https://github.com/bleachbit/bleachbit/archive/3.0.tar.gz : d992b9e11f0fc3612a2609bf6f77faeca2e39bb53556ee3259dc3ee210802a73
homepage   : https://www.bleachbit.org
license    : GPL-3.0-or-later
component  : security
summary    : BleachBit frees disk space and maintains privacy.
description: |
    BleachBit frees disk space and maintains privacy.
builddeps  :
    - pkgconfig(pygtk-2.0)
rundeps    :
    - python-gtk2
    - python-scandir
install    : |
    %make_install bindir=/usr/bin datadir=/usr/share
